package com.seriouslyhypersonic.processor.ktx

import com.tschuchort.compiletesting.KotlinCompilation
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import java.io.File

//region Mega-hack
/** Returns the list of KSP sources generated by the KSP compilation. */
@OptIn(ExperimentalCompilerApi::class)
val KotlinCompilation.Result.kspGeneratedSources: List<File>
    get() {
        val kspWorkingDir = workingDir.resolve("ksp")
        val kspGeneratedDir = kspWorkingDir.resolve("sources")
        val kotlinGeneratedDir = kspGeneratedDir.resolve("kotlin")
        val javaGeneratedDir = kspGeneratedDir.resolve("java")
        return kotlinGeneratedDir.listFilesRecursively() + javaGeneratedDir.listFilesRecursively()
    }

private fun File.listFilesRecursively(): List<File> {
    return listFiles()
        ?.flatMap { if (it.isDirectory) it.listFilesRecursively() else listOf(it) }
        ?: emptyList()
}

@OptIn(ExperimentalCompilerApi::class)
private val KotlinCompilation.Result.workingDir: File
    get() = outputDirectory.parentFile!!
//endregion
